name: Publish Blog

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          deploy-repo: https://github.com/vietanhtran16/vietanhtran16.github.io.git
          deploy-branch: master
